---
title: "Muller_beta_stats"
author: "Becca Maher"
date: "November 08, 2019"
output: html_document
---

## 1 Set up
```{r, include=FALSE}
## clear workspace------------------------
rm(list=ls())

# load libraries
library('phyloseq'); packageVersion('phyloseq')
library('vegan'); packageVersion('vegan')
library("usedist")
library("ggplot2")
library("microbiome")

## functions----------------------
pairwise.adonis.dm <- function(x,factors,stratum=NULL,p.adjust.m="bonferroni",perm=999){
  
  library(vegan)
  
  if(class(x) != "dist") stop("x must be a dissimilarity matrix (dist object)")
  
  co = as.matrix(combn(unique(factors),2))
  
  pairs = c()
  
  F.Model =c()
  
  R2 = c()
  
  p.value = c()
  
  
  
  for(elem in 1:ncol(co)){
    
    sub_inds <- factors %in% c(as.character(co[1,elem]),as.character(co[2,elem]))
    
    resp <- as.matrix(x)[sub_inds,sub_inds]
    
    ad = adonis(as.dist(resp) ~
                  
                  factors[sub_inds], strata=stratum[sub_inds], permutations=perm);
    
    pairs = c(pairs,paste(co[1,elem],'vs',co[2,elem]));
    
    F.Model =c(F.Model,ad$aov.tab[1,4]);
    
    R2 = c(R2,ad$aov.tab[1,5]);
    
    p.value = c(p.value,ad$aov.tab[1,6])
    
  }
  
  p.adjusted = p.adjust(p.value,method=p.adjust.m)
  
  pairw.res = data.frame(pairs,F.Model,R2,p.value,p.adjusted)
  
  return(pairw.res)
  }
```

## Analysis with Aquarickettsia
```{r}
# First import data from bioinformatic processing
load(file = "../data/ps_rar8663.RData")
ps
head(sample_sums(ps))
```
### Calculate distance matrices

```{r}
# Calculate all four distance matrices: weighted unifrac, unweighted unifrac, bray curtis, binary jaccard
ps_bc <- phyloseq::distance(ps, method = "bray")
ps_bj <- distance(ps, method = "jaccard", binary =TRUE)
```
### PERMANOVAs
```{r}
# PERMANOVA's with Adonis -  Permutational Multivariate Analasis of Variance
# Make a data frame from the sample_data
sampledf <- data.frame(sample_data(ps))

# Adonis individual tests
adonis(ps_bc ~ bleach*type, data = sampledf)
adonis(ps_bj ~ bleach*type, data = sampledf)

# all significant
## pairwise tests are all not significant (padj) probably too many comparisons
## maybe I should use the unadjusted pval?
pairwise.adonis.dm(ps_bc, sample_data(ps)$bleach.type, p.adjust.m = "fdr")
#pairwise.adonis.dm(ps_bj, sample_data(ps)$geno, p.adjust.m = "fdr")
```

### PERMDISPs
#### bleach
```{r}
anova(betadisper(ps_bc, sampledf$bleach, bias.adjust = TRUE))
anova(betadisper(ps_bj, sampledf$bleach, bias.adjust = TRUE))
```

#### type
```{r}
anova(betadisper(ps_bc, sampledf$type, bias.adjust = TRUE))
anova(betadisper(ps_bj, sampledf$type, bias.adjust = TRUE))
```
#### Interaction
```{r}
anova(betadisper(ps_bc, sampledf$bleach.type, bias.adjust = TRUE))
anova(betadisper(ps_bj, sampledf$bleach.type, bias.adjust = TRUE))

# pairwise tests
p.adjust(permutest(betadisper(ps_bc, sampledf$bleach.type, 
                              bias.adjust = TRUE), 
                   pairwise=TRUE)$pairwise$permuted, method = 'fdr')
#p.adjust(permutest(betadisper(ps_wu, sampledf$geno.trt, 
#                              bias.adjust = TRUE), 
#                   pairwise=TRUE)$pairwise$permuted, method = 'fdr')

```

## Analysis without Aquarickettsia
```{r}
# First import data from bioinformatic processing
load(file = "../data/ps_rar823.RData")
ps
head(sample_sums(ps))
```
### Calculate distance matrices

```{r}
# Calculate all four distance matrices: weighted unifrac, unweighted unifrac, bray curtis, binary jaccard
ps_bc <- phyloseq::distance(ps, method = "bray")
ps_bj <- distance(ps, method = "jaccard", binary =TRUE)
```
### PERMANOVAs
```{r}
# PERMANOVA's with Adonis -  Permutational Multivariate Analasis of Variance
# Make a data frame from the sample_data
sampledf <- data.frame(sample_data(ps))

# Adonis individual tests
adonis(ps_bc ~ bleach*type, data = sampledf)
adonis(ps_bj ~ bleach*type, data = sampledf)

# all significant
## pairwise tests are all not significant (padj) probably too many comparisons
## maybe I should use the unadjusted pval?
pairwise.adonis.dm(ps_bc, sample_data(ps)$bleach.type, p.adjust.m = "fdr")
#pairwise.adonis.dm(ps_bj, sample_data(ps)$geno, p.adjust.m = "fdr")
```

### PERMDISPs
#### bleach
```{r}
anova(betadisper(ps_bc, sampledf$bleach, bias.adjust = TRUE))
anova(betadisper(ps_bj, sampledf$bleach, bias.adjust = TRUE))
```

#### type
```{r}
anova(betadisper(ps_bc, sampledf$type, bias.adjust = TRUE))
anova(betadisper(ps_bj, sampledf$type, bias.adjust = TRUE))
```
#### Interaction
```{r}
anova(betadisper(ps_bc, sampledf$bleach.type, bias.adjust = TRUE))
anova(betadisper(ps_bj, sampledf$bleach.type, bias.adjust = TRUE))

# pairwise tests
p.adjust(permutest(betadisper(ps_bc, sampledf$bleach.type, 
                              bias.adjust = TRUE), 
                   pairwise=TRUE)$pairwise$permuted, method = 'fdr')
#p.adjust(permutest(betadisper(ps_wu, sampledf$geno.trt, 
#                              bias.adjust = TRUE), 
#                   pairwise=TRUE)$pairwise$permuted, method = 'fdr')

```
